# -*- coding: utf-8 -*-
"""Logistic_Regression_Binary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzoKkDJLdVLggmwauPEQ4hiMYchTp7nu
"""

#Logistic Regression using Binary Classification
#to find out the person at the age of 65 and 24 want to buy insurance or not
import pandas as pd

import matplotlib.pyplot as plt

dataset = pd.read_csv(r'/content/insurance_data.csv')

dataset

dataset['bought_insurance'].replace({'no':'0','yes':'1'} , inplace = True)

dataset

#visualizing the data points
plt.scatter(x='age' , y = 'bought_insurance' , data = dataset)

#model training
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(dataset[['age']],dataset['bought_insurance'] , test_size=0.2)

len(x_train)

x_train #21 rows are used for training our model

len(x_test)

x_test #6 rows are used for testing our model

len(y_train)

y_train

len(y_test)

y_test

#importing the logistic regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

lr.fit(x_train,y_train)

lr.predict(x_test)

lr.predict([[70]])

lr.predict([[24]])