# -*- coding: utf-8 -*-
"""LR(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Ezhz-TfiKJBEot-gI8plzdop7al2ReI
"""

#to predict premiums to be paid by a person of age 21 and 52 using linear regression!!!
import pandas as pd

import seaborn as sns

from sklearn import linear_model

df = pd.read_csv(r'term-insurance-dataset.csv')

df

sns.lmplot(x='age',y='premium',data=df)

reg = linear_model.LinearRegression()

reg.fit(df[['age']] , df[['premium']])

reg.predict([[21]])

reg.predict([[52]])

reg.coef_

reg.intercept_