# -*- coding: utf-8 -*-
"""lr(m).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJWFK3sHvPCGnCoeEalEfbm9-4hJyZQf
"""

#linear regression with multiple variables
#to predict the premium of a person with age = 43 height = 175  and weight = 82
#to predict the premium of a person with age = 51 height = 140  and weight = 45
import pandas as pd

from sklearn import linear_model

import seaborn as sns

df = pd.read_csv(r'/content/term-insurance-dataset.csv')

df

sns.barplot(x='age', y='premium' , data=df , hue ='premium')

reg = linear_model.LinearRegression()

reg.fit(df[['age','height','weight']] , df['premium'])

reg.coef_

reg.intercept_

reg.predict([[43,175,82]])

#verifying our prediction
5*43+0*175+5*82+2.2737367544323206e-13

reg.predict([[51,140,45]])

51*5+140*0+45*5+2.2737367544323206e-13